### PR TITLE
Add inmemory broker

### PR DESCRIPTION
**Pull request by vimukthi-git**
This first PR adds support for an in memory broker/backend to enable testing without any external queue server dependancies.

I also refactored the tests a little bit so that the tests can be run for all backends/brokers when needed.

### CODE REVIEW

**Comment by vimukthi-git** [comment]
@mikiquantum please ignore the tests for now, I will make them work on CI eventually.

**Comment by vimukthi-git** [comment]
@mikiquantum tests are fixed now.

**Comment by mikiquantum** [comment]
Maybe is gocelery specific, but can you explain what is the purpose of the `inmemory_backend` implementation? Isn't it the purpose of the backend to retrieve the message?
Not sure I understand the implementation as looks like the broker is taking care of that part?

**Comment by vimukthi-git** [comment]
@mikiquantum its specific to celery protocol, it differentiates between result storage vs actual message queuing. http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results
so the backend is to store results of computations

**Comment by mikiquantum** [comment]
Ok, thanks!

**Pull request merged**
